### ISSUE TITLE
lab2 замечания 1

### ISSUE THREAD

**Issue by Andrewbooq** [zaldaria/PP_lab2#1]
Всё сделано правильно. Далее делаем:
Сделать в printOk цикл из нескольких итераций вывода printf () с задержкой между выводами (sleep), чтобы общее время работы printOk  было около 20-30 секунд. Посмотреть как работает программа. Если будут проблемы - поправить.
Если всё хорошо, то нужно сделать передачу параметров. В main - pool.passQ переделать через указатель на функцию + 2 значения int, в q хранить не std::function, а структуры function <void()> + int + int (сохранять указатель на функцию и 2 значения).
А при вызове  f(); передавать их - f(struct.one, struct.two); 
В printOk()  печатать переданные значения

**Comment by zaldaria** [comment]
Загрузила последние изменения, программа завершается когда в очереди не остаётся задач

**Comment by Andrewbooq** [comment]
Принципиально - всё отлично, надо поправить мелочи:

1 Уже традиционное замечание, несоответствие типов.
В строке: `cntThreads = thread::hardware_concurrency();` какой тип возвращаемой переменной и какого типа cntThreads?
Ну и так далее по цепочке, какой тип у GetCntThreads, ...
Подскзка, size_t лучше не использовать в кроссплатфрменных приложениях, это платформозависимый тип данных, на Windows и на Linux у него может быть разный размер, компилятор может ругаться.

2 В `passQ` когда мы положили в очередь, мьютекс нужно отпускать, condition.notify_one(); уже не нужно под зажатым мьютексом делать, не так ли?

3 `#include <iomanip>` - для чего этот инклуд?

4 Нужно добавить user-friendly к нашей программе. Запускаю, вижу цифры. Что это? В сколько потоков посчитали, что считали и что получили... 

![image](https://github.com/user-attachments/assets/e02ce6c3-b8d9-4aa1-94a4-9004d4b9b032)

5 Ну и Makefile и сборка под Linux

6 printOk не нужна? можно удалить

**Comment by zaldaria** [comment]
Исправила:
1. Количество потоков хранится в переменной unsigned int n;
2. В passQ ограничила область видимости для объекта lock_guard<mutex> lg, после добавления в очередь объект выходит из области видимости, срабатывает деструктор и mutex отпускается перед выполнением condition.notify_one();
3. Убрала #include <iomanip>, больше оттуда ничего не используется;
4. Добавила user-friendly программе, теперь в консоль выводится количество доступных потоков и каждый раз из функции my_cos сообщается для какого значения считали косинус и чему он равен;
5. Сделала и загрузила Makefile, запустила код на Linux;
6. printOk не нужен - удалила;
7* Добавила в main() условие, не дающее выполняться программе, если число доступных потоков равно 0;

**Comment by Andrewbooq** [comment]
Ну всё же подушню. Не могу я на это спокойно смотреть.
Всё работает, под Linux собирается, запускается. НО
Если в винде можно было не заметить, то консоль линукса как светофор орет про Warnings.
Постарайся это поправить и можно приходить сдавать. 
![image](https://github.com/user-attachments/assets/96c70dd0-80db-47d9-bf7d-18aa8819dfb6)
![image](https://github.com/user-attachments/assets/4e2e8ca0-1e66-4814-add0-f232a8779e07)

**Comment by Andrewbooq** [comment]
Теорию буду спрашивать по всем лекциям, связанным с этой лабой. Тебя не было на лекции 24.10. К ней будет больше всего вопросов. Вот подсказка, о чём была лекция
указатели на функции
указатель на функцию с параметрами
шаблон std::function
std::bind для передачи указателя на функцию с параметрами
std::bind для передачи указателя на функцию с std::placeholder::_x
правило ноля правило пяти
Взаимоблокировка: проблема и решение, как избежать взаимоблокировок
Гибкая блокировка с помощью std::unique_lock
Выбор правильной гранулярности блокировки

**Comment by zaldaria** [comment]
Исправила, больше нет предупреждений, в main в цикле for теперь i не int, а тоже unsigned int, при сравнении с unsigned int n проблем нет
Про вопросы к этой лабе поняла, спасибо!

**Comment by Andrewbooq** [comment]
Да, теперь идеально!
